version: "3.5"

services:
  web:
    image: nginx:alpine
  app:
    image: nginx:alpine
    networks:
      app_net:
        ipv4_address: 172.18.0.10
  db:
    image: nginx:alpine
    networks:
    - app_net
    - db_net
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"
  db_net:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"
  default:
    external:
      name: web_net
